### ISSUE TITLE
Automatisk kobling av T-rør, endebunn, eksentrisk overgang

### ISSUE THREAD

**Issue by martin-mcgloin** [Lindab-Norge/ns3459-pricing-parser#3]
Endebunn = ESU

Eksentrisk overgang = RLU

Sentrisk overgang = RCU - Edit Jonas

Sirkulært t-stykke  / T-rør / t-stykke: TCPU

**Comment by JonasLindab** [comment]
Disse produktene skal være OK

**Comment by martin-mcgloin** [comment]
BOOM! You have been on fire - bra Jonas! Du er flink.
